name: CI/CD Evaluacion Parcial 3

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # PARTE 1: Build y Test
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/auy1102-eval:${{ github.sha }} .

      # Prueba unitaria dentro del contenedor
      - name: Run Tests inside Docker
        run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/auy1102-eval:${{ github.sha }} npm test

      # Subir imagen si tests pasan
      - name: Push to Docker Hub
        if: success()
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/auy1102-eval:${{ github.sha }}
          docker tag ${{ secrets.DOCKER_USERNAME }}/auy1102-eval:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/auy1102-eval:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/auy1102-eval:latest

  # PARTE 2: Seguridad
  security:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # --- NUEVO PASO PARA ARREGLAR EL ERROR DE SNYK ---
      - name: Install dependencies (Fix Lockfile)
        run: npm install
      # -------------------------------------------------

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Snyk Security Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --severity-threshold=high

      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
          command: quickview
          image: ${{ secrets.DOCKER_USERNAME }}/auy1102-eval:latest
